//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.Messenger.Server.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageNotRed
    {
        public int ID { get; set; }
        public long MessageID { get; set; }
        public int FromTocen { get; set; }
        public int ToTocen { get; set; }
    }
}
