//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ContactsID { get; set; }
        public int UserID { get; set; }
        public int ContactUserID { get; set; }
        public Nullable<bool> ContactDelete { get; set; }
        public string Order { get; set; }
    }
}
