//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.DataLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMessengerEntities : DbContext
    {
        public DBMessengerEntities()
            : base("name=DBMessengerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<MessageNotRed> MessageNotRed { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Message_Temp> Message_Temp { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
    }
}
