//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_Temp
    {
        public long MessageID { get; set; }
        public string Text { get; set; }
        public int FromTocen { get; set; }
        public int ToTocen { get; set; }
        public bool MessageDeleteFrom { get; set; }
        public bool MessageDeleteTo { get; set; }
        public System.DateTime DateTimeSend { get; set; }
        public Nullable<bool> situation { get; set; }
    }
}
